### ISSUE TITLE
API todo

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/moolah#1]
### Security

- [x] Add authentication
- [x] Add authorization
- [ ] Add csrf
- [x] Add helmet

### Design

- [ ] Test Firebase errors
- [ ] Add unit tests...(todo: figure out how to test firebase)
- [x] Adhere more closely to JSON API
- [x] Validations
- [ ] Add default resource attributes (for creation)

**Comment by jamesplease** [comment]
Closing in favor of newer issues
